# Generated by Django 5.2 on 2025-06-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_faceembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceembedding',
            name='is_face_captured',
        ),
        migrations.RemoveField(
            model_name='faceembedding',
            name='updated_at',
        ),
    ]
