# Generated by Django 5.2 on 2025-07-21 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_face_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('music', 'Music'), ('art', 'Art'), ('theater', 'Theater'), ('sports', 'Sports'), ('technology', 'Technology'), ('education', 'Education'), ('networking', 'Networking'), ('business', 'Business'), ('health', 'Health'), ('food', 'Food & Drink'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('social', 'Social Event'), ('other', 'Other')], max_length=20)),
                ('interest_score', models.FloatField(default=1.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
