# Generated by Django 5.2 on 2025-07-21 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_ticket_unique_together'),
        ('users', '0011_usereventpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('feedback_type', models.CharField(choices=[('click', 'Clicked'), ('purchase', 'Purchased'), ('dismiss', 'Dismissed'), ('manual', 'Manual Rating')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usereventpreference',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='usereventpreference',
            name='interactions_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usereventpreference',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='usereventpreference',
            index=models.Index(fields=['user', '-interest_score'], name='users_usere_user_id_9b69ce_idx'),
        ),
        migrations.AddIndex(
            model_name='usereventpreference',
            index=models.Index(fields=['category', '-interest_score'], name='users_usere_categor_24c4b4_idx'),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recommendationfeedback',
            unique_together={('user', 'event')},
        ),
    ]
