# Generated by Django 5.2 on 2025-05-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_ticket_payment_details_ticket_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
