# Generated by Django 5.2 on 2025-05-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_ticket_transaction_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='transaction_uuid',
        ),
    ]
