# Generated by Django 5.2 on 2025-05-12 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_ticket_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('user', 'event')},
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'payment_status'], name='events_tick_user_id_f52224_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event'], name='events_tick_event_i_706fce_idx'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
