# Generated by Django 5.2 on 2025-06-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_general_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in_method',
            field=models.CharField(blank=True, choices=[('face', 'Face'), ('qr', 'QR')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code_value',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
