# Generated by Django 5.2 on 2025-07-23 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_allowed_users_event_is_private_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='private_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_private'], name='events_even_is_priv_d7766c_idx'),
        ),
        migrations.AddField(
            model_name='guestinvitation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='guestinvitation',
            index=models.Index(fields=['token'], name='events_gues_token_ce6e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='guestinvitation',
            index=models.Index(fields=['event', 'email'], name='events_gues_event_i_44267f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guestinvitation',
            unique_together={('event', 'email')},
        ),
    ]
