# Generated by Django 5.2 on 2025-07-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_guestinvitation_alter_event_allowed_users_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guestinvitation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='guestinvitation',
            name='event',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_is_priv_d7766c_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_private',
        ),
        migrations.DeleteModel(
            name='GuestInvitation',
        ),
    ]
