# Generated by Django 5.2 on 2025-07-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_attendee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
