# Generated by Django 5.2 on 2025-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='attendees/qr_codes/'),
        ),
    ]
