# Generated by Django 5.2 on 2025-07-27 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_attendee_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='general_seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of general seats available', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='total_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Total number of attendees allowed', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of VIP seats available', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='vvip_seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of VVIP seats available', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
